### PR TITLE
feat: public service address swiper

### PR DESCRIPTION
**Pull request by Ibwedagama**
### Related
- [S47A2 - Layanan SIDATUK](https://app.clickup.com/t/2na0hg1)

### Changes
- refactor (public-service): create address swiper on media section
- refactor (public-service): add conditional checking to render address swiper

### Preview

**Mobile**

https://user-images.githubusercontent.com/33661143/197099558-93bf4dd7-7c96-4fc5-91b5-0c1da79932dd.mov

**Tablet**

https://user-images.githubusercontent.com/33661143/197099619-68e762d2-bdb0-4545-a43f-16582ada98c7.mov

**Dekstop**

https://user-images.githubusercontent.com/33661143/197099688-1a6e8560-aa31-4fe4-b495-2b679a289726.mov

### Evidence
title: feat public service address swiper
project: Portal Jabar
participants: @Ibwedagama @agunghide @naufalihsank @yoslie

### CODE REVIEW

**Review by naufalihsank — APPROVED** [review]
is the bullet pagination still appear when the `addresses` has only 1 item ?

**Comment by Ibwedagama** [comment]
> is the bullet pagination still appear when the `addresses` has only 1 item ?

Ah! I forgot about that haha. Should we hide them when it only has one address?

**Comment by naufalihsank** [comment]
> > is the bullet pagination still appear when the `addresses` has only 1 item ?
> 
> Ah! I forgot about that haha. Should we hide them when it only has one address?

image
According to the design yes, but i personally don't think that is a major problem

**Comment by Ibwedagama** [comment]
> > > is the bullet pagination still appear when the `addresses` has only 1 item ?
> > 
> > 
> > Ah! I forgot about that haha. Should we hide them when it only has one address?
> 
> image According to the design yes, but i personally don't think that is a major problem

All right I'm on it! Thanks for pointing that out @naufalihsank 🔥

**Comment by Ibwedagama** [comment]
Screen Shot 2022-10-21 at 10 21 18

done @naufalihsank 

changes here: https://github.com/jabardigitalservice/portal-jabar-frontend/pull/385/commits/a92eb141859567607f2c2a091d3a6b816183f7c5

**Review by naufalihsank — APPROVED** [review]

**Review by agunghide — APPROVED** [review]

**Review by yoslie — APPROVED** [review]

**Pull request merged**
